/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import java.net.Socket;

public class Library {
   public static void main (String[] args){
      Restaurant res1 = new Restaurant("res1",4, 1);
      Review review1 = new Review("good", "me", 4);
      res1.addReview(review1);
      System.out.println(review1);
      System.out.println(res1);

      System.out.println("Shops");
      Shop shop = new Shop("hghghgh", "hgurhgur", 5);
      Review shopReview = new Review("jigrj", "jirg",8);
         shop.addReview(shopReview);
      System.out.println(shop.toString());

      Theater theater = new Theater("Joker");

      theater.addMovie("joker");
      theater.addMovie("Bohemian Rhapsody");
      theater.addMovie("alalalla");
      System.out.println("Moviess");
theater.removeMovie("joker");
      Review movieReview = new Review("amazing", "me", 5 );
theater.addReview(movieReview);
      System.out.println(movieReview);
      System.out.println(theater.toString());
   }


}
